### ISSUE TITLE
Collision of dots

### ISSUE THREAD

**Issue by Etewilak** [silnrsi/font-awami#11]
The dots of U+067E and U+06CC collide in the following examples:
![image](https://user-images.githubusercontent.com/55674356/235421264-d09133be-de02-47dc-afa6-9389ca0c1de0.png)

**Comment by LornaSIL** [comment]
Thank you! Can you give us the text strings? (Paste the text into a comment)

**Comment by sharoncorrell** [comment]
I cannot reproduce this in the current version of the font.

![peh_yeh](https://github.com/silnrsi/font-awami/assets/7072107/f0a4bd0f-680e-430c-beec-358fe380e551)

**Comment by LornaSIL** [comment]
@Etewilak please reopen if this is still an issue. You will need to give us a document for testing purposes.
