### ISSUE TITLE
Missing support for Balochi Standard Alphabet's long E

### ISSUE THREAD

**Issue by arunvickram** [silnrsi/font-awami#12]
Hi!

I noticed that Awami is missing support for "U+0A89 ARABIC LETTER YEH WITH TWO DOTS BELOW AND DOT ABOVE". Basically it's missing support for this character which exists in Scheherazade and Lateef. This letter seems to be a part of the Balochi Standard Alphabet, and it seems to represent /e:/.

<img width="122" alt="U+0A89 ARABIC LETTER YEH WITH TWO DOTS BELOW AND DOT ABOVE" src="https://github.com/silnrsi/font-awami/assets/3953464/dcbb19fa-0787-4f5e-b4b3-c2271bfeb621">

I was wondering if there were any plans to implement this? Thanks!

**Comment by LornaSIL** [comment]
> Hi!
> 
> I noticed that Awami is missing support for "U+0A89 ARABIC LETTER YEH WITH TWO DOTS BELOW AND DOT ABOVE". Basically it's missing support for this character which exists in Scheherazade and Lateef. This letter seems to be a part of the Balochi Standard Alphabet, and it seems to represent /e:/.
> 
> <img alt="U+0A89 ARABIC LETTER YEH WITH TWO DOTS BELOW AND DOT ABOVE" width="122" src="https://private-user-images.githubusercontent.com/3953464/292577873-dcbb19fa-0787-4f5e-b4b3-c2271bfeb621.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNzg0NDAsIm5iZiI6MTcwMzI3ODE0MCwicGF0aCI6Ii8zOTUzNDY0LzI5MjU3Nzg3My1kY2JiMTlmYS0wNzg3LTRmNWUtYjRiMy1jMjI3MWJmZWI2MjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMjA0OTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2E0N2M2ZjM2MjZiMWFlMjkzZGI5MzNjODZiZTIwODhkYmJlZjA3ZWI0ZDE0NjgxN2FmMTFkNTE3ODA5MGNlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t-Y_rGxXGGJq0owaswtpeOSDjpdryjAdK7LwTKRLs0Y">
> I was wondering if there were any plans to implement this? Thanks!

This character was added for an African language...Fulfulde. I wonder if it's a different character you are thinking of. For example, this keyboard doesn't have a character that looks like that: https://help.keyman.com/keyboard/balochi_phonetic/1.5/balochi_phonetic

My understanding is that these are the characters required for Balochi:
```
[آ ا ب پ ت ٹ ج چ د ڈ ر ڑ ز ژ س ش ک گ ل م ن و ۆ ه ی ێ ے ئ ِ َ ُ ّ ْ]
```

**Comment by LornaSIL** [comment]
We will not plan to add U+0A89 unless there is better evidence. It does not appear to me to be what is being used in Balochi.
