### ISSUE TITLE
HarfBuzz requirement for script specification breaks Awami, can something be changed in order to make it more accessible?

### ISSUE THREAD

**Issue by niruvt** [silnrsi/font-awami#13]
I am using Awami Nastaliq with LuaLaTeX (from TeX Live 2024, updated fully on the date of posting). The placement of diacritics was fine until the last update, but suddenly I started getting incorrect output. I reported [a bug](https://github.com/latex3/luaotfload/issues/276) on the repository of [`luaotfload`](ctan.org/pkg/luaotfload) and asked [a question](https://tex.stackexchange.com/a/713681) on TeX.SE to find out (courtesy: Marcel Kruger) that a recent change in HarfBuzz which requires Graphite to be script-specific has caused this. So in LuaLaTeX terms, simply using `Renderer=Graphite` doesn't suffice, users have to also add `RawFeature={script=arab}`. Despite there existing a hack, I think this complicates the use of the font. It would be great if something could be changed at the font-level for it to be easy-to-use as it was before. This isn't really a 'bug', at the most may be a 'feature request'. Thanks for the attention and all the hard work so far. Cheers!

**Comment by LornaSIL** [comment]
Unfortunately the font _does_ require Graphite. We cannot implement the complexity of this font in OpenType. This means that for now anyway your workaround is the only solution. This sounds like a poor decision on the part of HB, but we do not have control over that.

**Comment by niruvt** [comment]
Thanks for the response. Of course, I wasn't suggesting to change the entire implementation. I was just trying to see if there exists any hack for this at the font level instead of the user level, but no problem! At least for LaTeX, there is a good news :-) The developer of `fontspec` [has fixed](https://github.com/latex3/fontspec/issues/456#issuecomment-2095027002) this issue now. I am closing this here since it is irrelevant for the font. I appreciate your support!
