### ISSUE TITLE
Sindhi Kaaf - U06AA

### ISSUE THREAD

**Issue by lateef-shaikh** [silnrsi/font-awami#3]
Can you please add U06AA in this font?

JIRA: ABS-2359

**Comment by LornaSIL** [comment]
Are you using Awami for the Sindhi language? Would you be able to upload an image of some words in Nastaliq style that use this character? Examples in isolate, initial, medial and final would be helpful

I can't promise we will add it, but if you can provide samples we will be more likely to add it.

**Comment by lateef-shaikh** [comment]
Hello,
Thank you for reply. Here is one sample
![Sindhi Kaaf](https://user-images.githubusercontent.com/44910801/101685750-23e83e80-3a36-11eb-8b5a-a58a5cfb6f06.png)

If you can release the VOLT project also then I'll try to add this letter. If you are not planning to include this letter then can I take the font project and create a new project with another name where I can include this letter? I am not familiar with Graphite therefore I'd need a Volt project for that.

Thanks

**Comment by LornaSIL** [comment]
Do you have an examples from a nicely typeset book? That would help us a lot in determining how to implement this.

**Comment by lateef-shaikh** [comment]
Actually there is no book because this style is not used for Sindhi. I want to invent something new and unique. So I am getting help from a calligrapher and then I am rotating it myself through software.

**Comment by LornaSIL** [comment]
Rotating the glyph does not look good and we cannot implement something that is rotated. If you can get a calligrapher to properly write the words the way a swash kaf should appear we would consider adding it. However, at this point it's unclear what such a glyph should look like in Nastaliq style.

**Comment by lateef-shaikh** [comment]
Thank you so much for a positive reply. I. Preparing a document for the calligrapher which will contain all two and three letter combinations. I'll reach out to you once it is ready and then you can tell me if you can consider it or not. In any case that document will help me in future if I try to make my own font.

**Comment by LornaSIL** [comment]
@lateef-shaikh I'm going to go ahead and close this issue. Feel free to reopen it if you find actual examples.
