### ISSUE TITLE
Issues with certain Kashmiri character combinations

### ISSUE THREAD

**Issue by Rishabhbhat** [silnrsi/font-awami#5]
1) U+06A9 ARABIC LETTER KEHEH + U+0654 ARABIC HAMZA ABOVE
Expected (for kashmiri word کٔٹ, with Noto Nastaliq)
![image](https://user-images.githubusercontent.com/55013228/131992555-732db846-8cec-4423-a2e0-91ca6a115e1a.png)
Actual:
![image](https://user-images.githubusercontent.com/55013228/131992618-caf06b49-69e3-4028-9e9e-86e154c68050.png)
The hamza goes to the right for some reason.
2) U+06CC ARABIC LETTER FARSI YEH + U+0654 ARABIC HAMZA ABOVE
This should combine like this: (word is نیٔتھٕر)
![image](https://user-images.githubusercontent.com/55013228/131992084-78b387aa-6514-4753-a38f-82128d440e29.png)
But this is how it does:
![image](https://user-images.githubusercontent.com/55013228/131992177-7d400c3d-fb8f-4ae0-b343-f947341a0ce8.png)
As you can see the dots expected below the 'ye' are missing.
There seems to be a general problem with the U+0654 ARABIC HAMZA ABOVE, including words like تٔمؠ , where the symbol goes below the "te"'s dots.
Expected:
![image](https://user-images.githubusercontent.com/55013228/131997397-c68899b1-75fd-4125-9f09-fad0225a9302.png)
Actual:
![image](https://user-images.githubusercontent.com/55013228/131997447-de027e30-f5b6-4605-8a67-d0c063b52339.png)

Sincerely hope these issues can be resolved as otherwise this is the perfect font for Kashmiri Perso-Arabic, and incredibly useful as a webfont.

**Comment by LornaSIL** [comment]
Thank you for your feedback! We will try to fix these issues when the font is next updated. We are happy to hear the font might work for Kashmiri if these are fixed.

**Comment by Rishabhbhat** [comment]
Yes, it is indeed the best, apart from this particular character. Noto Nastaliq mostly breaks :(

**Comment by Rishabhbhat** [comment]
Also ج + ٔ : we get this:
![image](https://user-images.githubusercontent.com/55013228/133725214-e29cfc6a-4d90-443b-b947-5bf1b8e5a046.png)
for word جٔنوٗبی.

**Comment by LornaSIL** [comment]
These have been fixed in the font update we are currently working on. The fixes will appear when the font is released.
