### ISSUE TITLE
Malay Jawi Gaf, Nya and Nga

### ISSUE THREAD

**Issue by Coolsium** [silnrsi/font-awami#7]
I wish for these letters to be added
the letters are as follows
ݢ(gaf)
ڽ (nya)
ڠ(nga)
I have some samples
![Screenshot 2022-03-13 220417(1)](https://user-images.githubusercontent.com/67449247/158063840-e862dd72-2f02-448f-a581-8f5434334f73.png)
![nga](https://user-images.githubusercontent.com/67449247/158063857-32251e63-f563-4dd7-ac12-8fa80098f60d.png)
I wish for these letters to be added as Malaysians actually use a form of the perso arabic script known as jawi, and ancient texts written in Jawi by hand look very similar to the jawi style, but nowadays is restricted to the naskh style due to no development of a nastaliq font for jawi. Malay is also a south asian language and you can check out jawi here https://en.wikipedia.org/wiki/Jawi_alphabet
Thank you in advance if these letters get added!

**Comment by Coolsium** [comment]
do note that ڽ in the middle for front position looks like this 
ڽڽڽ
![Screenshot 2022-03-14 082952](https://user-images.githubusercontent.com/67449247/158086431-46f721c9-4a52-4635-98a1-0f1b10517843.png)

**Comment by LornaSIL** [comment]
Thanks for your interest. We will add this to our list of things to consider for the next version. Currently we are working on bold which will be a higher priority than adding new characters.

**Comment by LornaSIL** [comment]
These have been added to the upcoming release of Awami Nastaliq.
