### ISSUE TITLE
Add Uyghur support

### ISSUE THREAD

**Issue by tommai4881** [silnrsi/font-awami#8]
The Uyghurs in China also use the nastaliq variant of Uyghur arabic.
![image](https://user-images.githubusercontent.com/34368690/181914975-74ae2bbc-9690-4444-9607-bf32ee4f85b5.png)

**Comment by LornaSIL** [comment]
We would be willing to consider this. Be aware that we will *not* support the "Arabic Presentation Forms" blocks as those are not recommended for use. We would need to evaluate which characters we are missing from the "Arabic" (0600..06FF) block. Would you be able to tell us which characters we are missing from that block?

**Comment by LornaSIL** [comment]
Since we do not support the Presentation Forms blocks (as they are not recommended for use), it looks like the only character we are missing is U+06AD. Is that correct?
Can you include a list of the combining marks required for Uyghur?

**Comment by tommai4881** [comment]
Yea, the letters in green cells, including u06d5, u0698, u06ad, u06be, u06c7, u06c6, u06c8, u06cb and u06c0

**Comment by tommai4881** [comment]
uyghur doesn't need combining marks

**Comment by tommai4881** [comment]
show me the example

**Comment by LornaSIL** [comment]
> show me the example

An example of what? We do not yet support the U+06AD character. We will add that to our list of things for future support? Otherwise, you are welcome to download the font and see whether it is useful.

**Comment by tommai4881** [comment]
Some examples of demonstration of Uyghur additions in Awami SIL
And about things for support, yes, Uyghur is usually written in Arabic
characters even outside China.

Vào Th 2, 8 thg 8, 2022 vào lúc 22:11 Lorna Evans <
***@***.***> đã viết:

**Comment by LornaSIL** [comment]
We have added U+06AD to the version of Awami Nastaliq that will be released soon.
